Final Inspector Update
tommy-russoniello/juml pull request #42
Opened 2017-12-06 11:07 UTC by tommy-russoniello

- Fully implemented what @Tmilly started with the inspectors for new functionality.
- Incorporated @quinnminnich 's action classes for changing line direction/type
- Fixed various bugs

2017-12-06 12:18 UTC, scarroll142 approved these changes
Looks good besides the one line of conflict in note.java. should be a quick fix though

2017-12-06 13:55 UTC, quinnminnich requested changes
Hmm; when I downloaded it, I got an error every time I tried to select a connector (there appears to be a problem loading the inspector). Did that work for you?

2017-12-06 15:31 UTC, Tmilly approved these changes
Looks good Tommy, I played around with it and it works very well and clean. I didn't get any error when I ran the code

2017-12-07 00:09 UTC, quinnminnich approved these changes

2017-12-07 01:20 UTC, merged